version: 2
jobs:
  build:
    working_directory: ~/breakfast
    docker:
      - image: circleci/python:3.7.3-node
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/breakfast?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: breakfast
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: "Python Dependencies"
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - restore_cache:
          key: npm-requirements-{{ checksum "package.json" }}
      - run:
          name: "Node Dependencies"
          command: |
            npm install
      - save_cache:
          key: npm-requirements-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: "Build Frontend"
          command: |
            npm run build
      - run:
          name: "Django collectstatic"
          command: |
            pipenv run python manage.py collectstatic --no-input
      - run:
          name: "Backend tests"
          command: |
            pipenv run "coverage run --omit */.venv/* manage.py test"
      - run:
          name: "Backend Coverage"
          command: |
            pipenv run "coverage html -d test-results"
            pipenv run "coverage report --fail-under 95"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
